# -*- coding: utf-8 -*-
"""Simple_Pytourch_ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nqVl7f-isSKoWZbLiOJbMp6v5z6E0ymP

Simple PyTorch ANN
"""

import torch
import torch.nn as nn

model = nn.Sequential(
    nn.Linear(2,4),
    nn.ReLU(),
    nn.Linear(4,1)
)

X=torch.tensor([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
y=torch.tensor([[0.],[1.],[1.],[0.]])

"""Loss Function and Optimizer

MSELoss measures prediction error

Adam  optimizer updates weights  efficiently
"""

loss_fn=nn.MSELoss()
opt=torch.optim.SGD(model.parameters(),lr=0.01)

for _ in range(1000):
    opt.zero_grad()
    loss=loss_fn(model(X),y)
    loss.backward()
    opt.step()

"""Model inference

we print the models predictions after traning
"""

print(model(X))